### ISSUE TITLE
Hello from Hydra :)

### ISSUE THREAD

**Issue by omry** [enlite-ai/maze#7]
Thanks for using Hydra!
I see that you are using Hydra 1.1 already which is great. One thing that is really recent is the ability to configure the config searchpath from the primary config.
You can learn about it [here](https://hydra.cc/docs/next/advanced/search_path).

This can probably eliminate the need of your users to even know what a ConfigSearchpathPlugin is.

Feel free to jump into the Hydra chat if you have any questions.

**Comment by kristiankozak** [comment]
Hi @omry, thanks a lot for reaching out and for the suggestion!

It sounds very interesting, if we could make the custom config easier for our users, that would definitely be great. We will look into it and get back to you if we have any follow-up questions.

Thanks for sharing Hydra, it provides a very nice config foundation for Maze.

**Comment by omry** [comment]
I am actually not sure hydre.searchpath is in the recent dev release.
You may have to install it from master if it's not. (The next dev release should be in a week or two).
